name: Build and Publish on Github Packages
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: MrRamych/gradle-actions/openjdk-12@3.1
        with:
          args: dockerCreateDockerfile
      - name: Publish to Package Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: ninjawarrior1337/hanamaru/hanamaru
          username: $GITHUB_ACTOR
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          workdir: build/docker
